---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- ./object-detection-rest-imagestream.yaml

namespace: "retail-rhods-project"

patchesStrategicMerge:
- ./deployment-patches.yaml
